# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 130985f44d351fa3e46d9c0a2cdb7672e2d9747dfdbfe4f84c5a5ee3b46362732077e21ffef62c8f18c80cc9a0b7aaa07962200cd3f4653bfcfde5187e7b359f

test:
  secret_key_base: 00db854b4aa8ea32fc7ef4eb4740ba01d9e9834c69e65de982f98f9cc178e0b176e524c38b9fd6490780afe6f30e8a610871214e227b56e7783bbe1c9fdd5546

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
